version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Prettier Check
          command: npm run prettier
      - run:
          name: Test
          command: npm run test
