version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install && npm install -D codecov jest-junit

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Prettier Check
          command: npm run prettier

